# Generated by Django 2.2.1 on 2019-05-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_loan_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
