# Generated by Django 2.2.1 on 2019-05-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_amount',
            new_name='loan_amt',
        ),
    ]
