# Generated by Django 2.2.1 on 2019-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190503_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amt',
            field=models.PositiveIntegerField(),
        ),
    ]
