# Generated by Django 2.2.1 on 2019-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190507_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_goal',
            field=models.PositiveIntegerField(default=500000),
            preserve_default=False,
        ),
    ]
