# Generated by Django 2.2.1 on 2019-05-13 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_funding_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
