# Generated by Django 2.2.1 on 2019-05-13 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_funding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 27, 17, 54, 10, 694905)),
        ),
    ]
