# Generated by Django 2.2.1 on 2019-05-13 17:59

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190513_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_date',
            field=models.DateField(default=projects.models.Project.return_date_time),
        ),
    ]
