# Generated by Django 2.2.1 on 2019-05-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190513_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funding_date',
        ),
    ]
