# Generated by Django 2.2.1 on 2019-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_project_funding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='application_fee',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='borrow_rate',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='borrow_term',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='loan_total',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='origination_fee',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=2),
            preserve_default=False,
        ),
    ]
