# Generated by Django 2.2.1 on 2019-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20190515_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='borrow_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='origination_fee',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
