# Generated by Django 2.2.1 on 2019-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190515_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='origination_fee',
            field=models.FloatField(),
        ),
    ]
