# Generated by Django 2.2.1 on 2019-05-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190515_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='borrow_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='loan_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='origination_fee',
            field=models.PositiveIntegerField(),
        ),
    ]
