# Generated by Django 2.2.1 on 2019-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('D', 'Deny'), ('A', 'Approve'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
