# Generated by Django 2.2.1 on 2019-06-03 14:40

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20190603_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_date',
            field=models.DateField(default=projects.models.Project.return_date_time),
        ),
    ]
