# Generated by Django 2.2.1 on 2019-06-03 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_funding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=models.TextField(), max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 18, 11, 40, 39, 222899)),
        ),
    ]
