# Generated by Django 2.2.1 on 2019-06-03 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20190603_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 18, 11, 59, 22, 281217)),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
