# Generated by Django 2.2.1 on 2019-06-04 15:00

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20190603_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_date',
            field=models.DateField(default=projects.models.Project.return_date_time),
        ),
    ]
