# Generated by Django 2.2.1 on 2019-06-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20190604_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.TextField(blank=True),
        ),
    ]
