# Generated by Django 2.2.3 on 2019-09-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20190725_1727'),
        ('projects', '0032_auto_20190620_1622'),
    ]

    operations = [
    ]
