# Generated by Django 2.2.1 on 2019-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190607_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_underwriter',
            field=models.BooleanField(default=False),
        ),
    ]
