# Generated by Django 2.2.1 on 2019-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='ide',
            field=models.CharField(default='', max_length=50),
        ),
    ]
