# Generated by Django 2.2.1 on 2019-07-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0002_contractinfo_ide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractinfo',
            name='ide',
        ),
    ]
