# Generated by Django 2.2.1 on 2019-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0004_contractinfo_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='block_numb',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
