# Generated by Django 2.2.1 on 2019-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0006_auto_20190701_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLNATSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lnat_held', models.IntegerField()),
                ('unix_time', models.IntegerField()),
                ('day_number', models.IntegerField()),
            ],
        ),
    ]
