# Generated by Django 2.2.1 on 2019-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0007_dailylnatsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylnatsum',
            name='user_address',
            field=models.CharField(default='0xc93E1E4F77Eb503BDFA75a2E4dE24840E8e8089E', max_length=50),
            preserve_default=False,
        ),
    ]
