# Generated by Django 2.2.1 on 2019-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0008_dailylnatsum_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylnatsum',
            name='lnat_held',
            field=models.BigIntegerField(),
        ),
    ]
