# Generated by Django 2.2.1 on 2019-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0009_auto_20190711_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylnatsum',
            name='lnat_held',
            field=models.CharField(max_length=50),
        ),
    ]
