# Generated by Django 2.2.1 on 2019-07-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0010_auto_20190711_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyLNATSum',
            new_name='LNATSum',
        ),
    ]
