# Generated by Django 2.2.1 on 2019-07-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractcalls', '0011_auto_20190711_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnatsum',
            name='unix_time',
        ),
    ]
